version: 2
executorType: machine
jobs:
  build:
    environment:
      GOPATH: /home/circleci/.go_workspace
    working_directory: $GOPATH/src/github.com/docker/libentitlement
    steps:
      - checkout
      - run: go get -u github.com/golang/lint/golint github.com/fzipp/gocyclo github.com/client9/misspell/cmd/misspell github.com/gordonklaus/ineffassign
      - run: cd $GOPATH/src/github.com/docker/libentitlement && make test
