version: 2
executorType: machine
jobs:
  build:
    environment:
      GOPATH: /home/circleci/.go_workspace
    working_directory: $GOPATH/src/github.com/docker/libentitlement
    steps:
      - checkout
      - run: cd $GOPATH/src/github.com/docker/libentitlement && test -z $(go tool vet -printf=false . 2>&1 | grep -v vendor/ | tee /dev/stderr)
      - run: cd $GOPATH/src/github.com/docker/libentitlement && test -z $(gofmt -s -l . | grep -v vendor/ | tee /dev/stderr)
      - run: cd $GOPATH/src/github.com/docker/libentitlement && go test .